matrix:
  include:
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4

before_install: brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/nativeos
  - ln -s $PWD $(brew --repo)/Library/Taps/nativeos/homebrew-i386-elf-toolchain
  - brew tap --repair

script:
  - brew install -v i386-elf-binutils
  - brew install -v i386-elf-gcc
  - brew install -v i386-elf-gdb

